name: e_commerce
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

#----------------PACKAGES--------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.6.0
  intl: ^0.20.0
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7

  # Icons
  iconsax_plus: ^1.0.0
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0




flutter:


  uses-material-design: true


